### ISSUE TITLE
Week 12 Project Assignment Feedback

### ISSUE THREAD

**Issue by tienyulin** [YYB-SOA/api-cafemap#7]
1. Please implement `request object` for parsing HTTP request url/body
2. Please rewrite `view` to return ApiResult objects
https://github.com/YYB-SOA/api-cafemap/blob/8d798e29ad90c91cbc348a0441fbe420f9a7e77f/app/application/controller/app.rb#L73-L78
https://github.com/YYB-SOA/api-cafemap/blob/8d798e29ad90c91cbc348a0441fbe420f9a7e77f/app/application/controller/app.rb#L95-L98

3. Services should return `ApiResult objects`
4. Please implement `response object` and `representer object` for API response.
5. Please implement acceptance tests.

**Comment by ShiuanShr** [comment]
Except 5, the issues are solved.
Due to the BADM presentation, We' ll start to work on another repo app tomorrow.

**Comment by ShiuanShr** [comment]
The acceptance test is done
